### ISSUE TITLE
Black Image Instead of 2D Intensity Histogram

### ISSUE THREAD

**Issue by ScientistRachel** [fiji/Colocalisation_Analysis#74] opened 2022-07-01 21:20 UTC
When running Coloc 2, the 2D Intensity Histogram, as well as any other images in the dropdown menu (channel 1 max projection, etc.) show up as black images.  If I run my cursor over the images, I see varied pixel values on the Fiji toolbar, but those variations are not visible:

![coloc 2 - new version of Fiji](https://user-images.githubusercontent.com/65371136/176967690-567d5c52-35d9-48f2-8b17-de4e11f6a2ba.jpg)

I am comparing this behavior to an older installation of Fiji.  If I use the same images in both the newer version (image above), I get the following images in the older installation:

![coloc 2 - old version of Fiji](https://user-images.githubusercontent.com/65371136/176967740-ad46c931-7b65-4b9c-b141-5d17e5f238b0.jpg)

We would like to be able to run Coloc 2 with some of the updates that have been applied in the newer version of Fiji.  Are there any options to make the information in the scatterplot visible with the most recent updates to Fiji?  Thank you for any suggestions!

**Comment by chalkie666** [comment] 2022-07-01 21:54
@ScientistRachel this appears to be a new bug somewhere in Fiji, unless thr code for coloc2 changed recently. Others have also seen this. @ctrueden any clues what changes might have lead to this?

**Comment by ctrueden** [comment] 2022-07-04 04:24
@chalkie666 I'm on vacation this week, but will try to investigate after I return on July 11th.

**Comment by ScientistRachel** [comment] 2022-10-07 19:28
In case it helps with this bug, it turns out you can sometimes see part of the scatter plot.  On some data sets, if I turn the Log checkbox off in the bottom right corner you can see the brightest part of the peak as a small region of the scatter plot.  So perhaps it is problem with the colormap scaling? Also, the ability to export the data as a list is intact, so the histogram is being generated, just not displayed.

**Comment by FFeiner98** [comment] 2024-08-27 11:32
Why is this still not fixed?

**Comment by chalkie666** [comment] 2024-08-27 11:43
Hi,

Maybe you would like to help find some resources so it can be fixed by
someone?

Remeber:  This stuff is free as in freedom, not as in free beer or lunch.

Cheers

Dan

**Comment by FFeiner98** [comment] 2024-08-27 12:11
Hey Dan! I would love to help fix this issue. I might have let my emotions get the best of me. Sorry! I have read so much about this issue but the only "solution" is to get an old Fiji version. At this point using Coloc2 would be very uncertain. I have been trying to get the same results using Coloc2 and JACoP to verify that Coloc2 is giving trustable results, but with no luck. Coloc2 does not let you adjust the threshold like JACoP does. So this makes it difficult.

**Comment by ctrueden** [comment] 2024-08-27 16:09
I did some digging. The bug happens with ImageJ 1.54c (`jars/ij-1.54c.jar`) but not with ImageJ 1.52a. I'm bisecting further now to figure out which version of ImageJ broke the plot display.

**Comment by ctrueden** [comment] 2024-08-27 16:29
The first release of ImageJ with the problem is 1.53o. The commit that broke it is imagej/ImageJ@834d41b87163c879dc623ab2ee4d7121d6b2ea07, specifically the changes to `FloatProcessor`.

Not surprisingly, it is a change to how ImageJ computes the min/max autoscaling for 32-bit floating point images. We can probably work around the breakage by introducing an explicit `setMinAndMax` call or similar into the 2D histogram images. Investigating now.

**Closed** 2024-08-27 17:14 UTC

**Comment by ctrueden** [comment] 2024-08-27 17:54
I made a new release including this fix, and uploaded it to the core update site. Update your Fiji and you should receive it.

**Comment by chalkie666** [comment] 2024-08-27 19:56
@FFeiner98  just in case .... the whole point of the Costes Auto thresholds method implemented in coloc2 and described in thr paper linked in the docs, is that manual threshold setting is a bad idea. You can get any answer you like. Autothreshokds set them above where three us zero corelation. Also you should set the region of interest ti only include where the coloc is suggested to happen. Usually not the whole image. Lastly, you need lots of pixels , maybe from many images, birder for the statistical methods described in the papers to work properly. Not enough pixels and must fail. Understand the maths in use before you get started. Forget manual thresholds. 

Best
Dan

**Comment by ctrueden** [comment] 2024-08-27 21:58
Regarding manual thresholding: see also #65.

**Comment by FFeiner98** [comment] 2024-08-28 07:35
@ctrueden You are wonderful! Thank you! 

@chalkie666 Thank you for the explanation! I totally agree that manual thresholds are not a great way to do co-localisation analysis. At that point the goal to use the manual threshold was to test the same image in Coloc2 and JACoP to verify if the error of the histogram did not also mean the analysis was incorrect. But now that it is fixed its irrelevant :)

**Comment by chalkie666** [comment] 2024-08-28 20:27
@FFeiner98 you might not get comparable results. The thresholds can be defined as lower than,  or equal or lower than. Inclusive or exclusive if the threshold value. It's one way or the other in coloc2, I forget which. And might be different in Jacop. Especially for images in 8 bit range, or a small dynamic range at low end of 12 or 26 bit ranges... the difference between inclusive or exclusive matters. It's not clearly defined in the original paper if I remember correctly. Devils in the details.....

Testing data must contain enough pixels for the ststdntj work. 

I wonder if converting to float  and normalising the range 0 to 95 percent intensity to 0.0 to 1.0, and adding a tiny amount of noise would help with the inclusive or exclusive threshold issue. 

Don't forget to subtract any non zero camera offdlset or bias, or PMT non zero bias. Take dark images. 

Cheers!
